#!/bin/sh
set -e
cat <<FOE |
#ifdef __x86_64__
#include <asm/unistd.h>
#endif
FOE
	gcc -E -dD "$@" - |
	grep '__NR' |
	sed -e 's/#define \(.*\?\) .*/\0\n"\1" \1/' |
	gcc -E -x c - - |
	grep -v '#' |
	grep '[0-9]' |
    sed -e 's/"__NR_\(.*\)" \(.*\)/\/* \2 *\/ [__NR_\1] = "\1",/g' |
	sort -k2 -n | 
	awk '{print$6;}'
	